server:
  prot: 0

spring:
  application:
    name: user-service

  h2:
    console: true
    settings:
      web-allow-others: true
    path: /h2-console

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  client:
    service-url:
      defaultZone: http://127.0.0.1:7789/eureka
    fetch-registry: true
    register-with-eureka: true

greeting:
  message: Welcome to the Simple E-commerce.

logging:
  level:
    com.example.userservice.client: DEBUG